package org.elasticsearch.plugin.swagger.model;

import java.util.List;
import java.util.Map;

/**
 * The API Declaration provides information about an API exposed on a resource.
 */

public class ApiDeclaration extends SwaggerModel {

    /**
     * Gets or sets the swagger version.
     */
    private String swaggerVersion;

    /**
     * Provides the version of the application API.
     */
    private String apiVersion;

    /**
     * The root URL serving the API. This field is important as while it is common to have the
     * Resource Listing and API Declarations on the server providing the APIs themselves, it is not
     * a requirement. The API specifications can be served using static files and not generated by
     * the API server itself, so the URL for serving the API cannot always be derived from the URL
     * serving the API specification.
     */
    private String basePath;

    /**
     * The relative path to the resource, from the basePath, which this API Specification
     * describes.
     */
    private String resourcePath;

    /**
     * A list of the APIs exposed on this resource.
     */
    private List<Api> apis;

    /**
     * A list of the models available to this resource. Note that these need to be exposed
     * separately for each API Declaration.
     */
    private Map<String, Model> models;

    /**
     * A list of MIME types the APIs on this resource can produce. This is global to all APIs but
     * can be overridden on specific API calls.
     */
    private List<String> produces;

    /**
     * A list of MIME types the APIs on this resource can consume. This is global to all APIs but
     * can be overridden on specific API calls.
     */
    private List<String> consumes;

    /**
     * A list of authorizations schemes required for the operations listed in this API declaration.
     * Individual operations may override this setting. If there are multiple authorization schemes
     * described here, it means they're all applied.
     */
    private Map<String, Authorization> authorizations;

    public ApiDeclaration(String swaggerVersion, String apiVersion, String basePath, String resourcePath, List<Api> apis, Map<String, Model> models) {
        this(swaggerVersion, apiVersion, basePath, resourcePath, apis, models, null, null, null);
    }
    public ApiDeclaration(String swaggerVersion, String apiVersion, String basePath, String resourcePath, List<Api> apis, Map<String, Model> models, List<String> produces, List<String> consumes, Map<String, Authorization> authorizations) {
        this.swaggerVersion = swaggerVersion;
        this.apiVersion = apiVersion;
        this.basePath = basePath;
        this.resourcePath = resourcePath;
        this.apis = apis;
        this.models = models;
        this.produces = produces;
        this.consumes = consumes;
        this.authorizations = authorizations;
    }
}